
-- 
-- Editor server script for DB table ProductID
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `ProductID` (
	`id` int(10) NOT NULL auto_increment,
	`ProductID` varchar(255) default NULL,
	`ProductName` varchar(255) default NULL,
	`ProductCode` varchar(255) default NULL,
	`PHeight` varchar(255) default NULL,
	`PWidth` varchar(255) default NULL,
	`Cost` varchar(255) default NULL,
	`Price` varchar(255) default NULL,
	`Percentage` varchar(255) default NULL,
	`CustomerIDs` varchar(255) default NULL,
	`Discontinued` varchar(255) default NULL,
	`CreateDate` timestamp,
	`AlterDate` timestamp,
	PRIMARY KEY  (`id`)
);

