<?php

/*
 * Editor server script for DB table ProductID
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'ProductID' )
	->fields(
		Field::inst( 'ProductID' ),
		Field::inst( 'ProductName' ),
		Field::inst( 'ProductCode' ),
		Field::inst( 'PHeight' ),
		Field::inst( 'PWidth' ),
		Field::inst( 'Cost' ),
		Field::inst( 'Price' ),
		Field::inst( 'Percentage' ),
		Field::inst( 'CustomerIDs' ),
		Field::inst( 'Discontinued' ),
		Field::inst( 'CreateDate' )
			->validator( 'Validate::dateFormat', 'm-d-y' )
			->getFormatter( 'Format::date_sql_to_format', 'm-d-y' )
			->setFormatter( 'Format::date_format_to_sql', 'm-d-y' ),
		Field::inst( 'AlterDate' )
			->validator( 'Validate::dateFormat', 'm-d-y' )
			->getFormatter( 'Format::date_sql_to_format', 'm-d-y' )
			->setFormatter( 'Format::date_format_to_sql', 'm-d-y' )
	)
	->process( $_POST )
	->json();

